version: '16.0'

services:
 tracer-db:
   container_name: dev-tracer-db
   image: postgres:16.0-alpine
   ports:
     - "5432:5432"
   environment:
     POSTGRES_DATABASE: "dev_tracer_db"
     POSTGRES_USER: root
     POSTGRES_PASSWORD: root